name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      # Github Repository Secrets를 통해 환경 변수 파일을 생성
      - name: Create .env File for Production
        run: |
          echo "REACT_APP_GRAPHQL_ENDPOINT=${{ secrets.REACT_APP_GRAPHQL_ENDPOINT }}" >> .env
          echo "REACT_APP_CLOUD_STORAGE_BASE=${{ secrets.REACT_APP_CLOUD_STORAGE_BASE }}" >> .env
          echo "REACT_APP_FIREBASE_APIKEY=${{ secrets.REACT_APP_FIREBASE_APIKEY }}" >> .env
          echo "REACT_APP_FIREBASE_DOMAIN=${{ secrets.REACT_APP_FIREBASE_DOMAIN }}" >> .env
          echo "REACT_APP_AWS_S3_BUCKET_NAME=${{ secrets.REACT_APP_AWS_S3_BUCKET_NAME }}" >> .env
          echo "REACT_APP_AWS_ACCESS_KEY_ID=${{ secrets.REACT_APP_AWS_ACCESS_KEY_ID }}" >> .env
          echo "REACT_APP_AWS_SECRET_ACCESS_KEY=${{ secrets.REACT_APP_AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "REACT_APP_AWS_S3_URL=${{ secrets.REACT_APP_AWS_S3_URL }}" >> .env
          cat .env

      - name: Graphql Codegen
        run: yarn run codegen --watch

      - name: Build
        run: yarn run build
        env:
          NODE_ENV: production
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          PERSONAL_TOKEN: ${{secrets.GH_ACTIONS_TOKEN}}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
          SCRIPT_MODE: true